name: 'Create Issues'
description: 'Create issues from directory of files'

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  project-file:
    description: Path to a markdown file with front matter content
    required: false
  project-name:
    description: Project name to use
    required: false
  project-description:
    description: Description of project
    required: false
  column-names:
    description: 'Column names to create and add issues to'
    required: false

runs:
  using: 'node12'
  main: 'index.js'
