name: 'Create Issues'
description: 'Create issues from directory of files'

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: 'node12'
  main: 'index.js'
